/**
 * DLOSy20 - Drawing Mode
 * Draw shapes on canvas → convert to LR waveform (XYscope principle)
 * Supports multiple drawing slots and per-step waveform assignment
 */

class DrawingMode {
  constructor() {
    // Drawing slots (8 slots)
    this.slots = [
      { name: 'Draw 1', points: [], waveX: [], waveY: [] },
      { name: 'Draw 2', points: [], waveX: [], waveY: [] },
      { name: 'Draw 3', points: [], waveX: [], waveY: [] },
      { name: 'Draw 4', points: [], waveX: [], waveY: [] },
      { name: 'Draw 5', points: [], waveX: [], waveY: [] },
      { name: 'Draw 6', points: [], waveX: [], waveY: [] },
      { name: 'Draw 7', points: [], waveX: [], waveY: [] },
      { name: 'Draw 8', points: [], waveX: [], waveY: [] },
    ];
    this.activeSlot = 0;
    this.isDrawing = false;
    this.autoSlotCycle = false; // Auto-cycle through slots on each step

    // Canvas
    this.canvas = null;
    this.ctx2d = null;
    this.canvasSize = 256;

    // Audio: real-time preview oscillator using PeriodicWave
    this.previewOsc = null;
    this.previewGain = null;
    this.isPreviewPlaying = false;

    // Waveform resolution
    this.waveResolution = 256;
  }

  init() {
    this.buildUI();
    this.bindControls();
  }

  // ===== UI =====

  buildUI() {
    const container = document.getElementById('drawing-panel');
    if (!container) return;

    container.innerHTML = `
      <div class="panel-title">
        DRAWING MODE
        <div class="draw-header-controls">
          <button id="draw-auto-cycle" class="small-btn">AUTO CYCLE</button>
          <button id="draw-preview-btn" class="small-btn">♪ PREVIEW</button>
          <button id="draw-clear-btn" class="small-btn">CLEAR</button>
        </div>
      </div>
      <div class="draw-slot-tabs" id="draw-slot-tabs">
        <!-- generated by JS -->
      </div>
      <div class="draw-main-area">
        <div class="draw-canvas-wrapper">
          <canvas id="draw-canvas" width="256" height="256"></canvas>
          <div class="draw-crosshair-h" id="draw-crosshair-h"></div>
          <div class="draw-crosshair-v" id="draw-crosshair-v"></div>
        </div>
        <div class="draw-waveform-preview">
          <div class="draw-wave-label">L (X)</div>
          <canvas id="draw-wave-l" width="256" height="48"></canvas>
          <div class="draw-wave-label">R (Y)</div>
          <canvas id="draw-wave-r" width="256" height="48"></canvas>
        </div>
      </div>
      <div class="draw-info-bar">
        <span id="draw-point-count" class="draw-info">Points: 0</span>
        <span id="draw-coords" class="draw-info"></span>
      </div>
    `;

    this.buildSlotTabs();
    this.initCanvas();
  }

  buildSlotTabs() {
    const container = document.getElementById('draw-slot-tabs');
    if (!container) return;
    container.innerHTML = '';

    this.slots.forEach((slot, i) => {
      const tab = document.createElement('button');
      tab.className = 'draw-slot-tab' + (i === this.activeSlot ? ' active' : '');
      tab.textContent = slot.name;
      tab.dataset.slot = i;
      tab.addEventListener('click', () => {
        this.activeSlot = i;
        document.querySelectorAll('.draw-slot-tab').forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
        this.redrawCanvas();
        this.updateWaveformPreview();
      });
      container.appendChild(tab);
    });
  }

  initCanvas() {
    this.canvas = document.getElementById('draw-canvas');
    if (!this.canvas) return;
    this.ctx2d = this.canvas.getContext('2d');

    this.canvas.addEventListener('mousedown', (e) => this.onMouseDown(e));
    this.canvas.addEventListener('mousemove', (e) => this.onMouseMove(e));
    this.canvas.addEventListener('mouseup', () => this.onMouseUp());
    this.canvas.addEventListener('mouseleave', () => this.onMouseUp());

    // Touch
    this.canvas.addEventListener('touchstart', (e) => { e.preventDefault(); this.onTouchStart(e); }, { passive: false });
    this.canvas.addEventListener('touchmove', (e) => { e.preventDefault(); this.onTouchMove(e); }, { passive: false });
    this.canvas.addEventListener('touchend', () => this.onMouseUp());

    this.redrawCanvas();
  }

  bindControls() {
    document.getElementById('draw-clear-btn')?.addEventListener('click', () => {
      this.slots[this.activeSlot].points = [];
      this.slots[this.activeSlot].waveX = [];
      this.slots[this.activeSlot].waveY = [];
      this.redrawCanvas();
      this.updateWaveformPreview();
      this.updatePointCount();
    });

    document.getElementById('draw-preview-btn')?.addEventListener('click', () => {
      this.togglePreview();
    });

    // Auto-cycle ON/OFF toggle
    document.getElementById('draw-auto-cycle')?.addEventListener('click', () => {
      this.autoSlotCycle = !this.autoSlotCycle;
      const btn = document.getElementById('draw-auto-cycle');
      if (btn) {
        btn.classList.toggle('vco-on', this.autoSlotCycle);
      }
    });
  }

  // Advance to next slot (called from step sequencer on each step tick)
  advanceSlot() {
    if (!this.autoSlotCycle) return;
    this.activeSlot = (this.activeSlot + 1) % this.slots.length;
    // Update UI tabs
    document.querySelectorAll('.draw-slot-tab').forEach((t, idx) => {
      t.classList.toggle('active', idx === this.activeSlot);
    });
    this.redrawCanvas();
    this.updateWaveformPreview();

    // Switch VCO Loop audio buffer if running in drawing mode
    if (window.vcoLoop && vcoLoop.isOscRunning && vcoLoop.isDrawingOsc) {
      vcoLoop.switchDrawBuffer(this.activeSlot);
    }
  }

  // ===== DRAWING =====

  getCanvasPos(e) {
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    return {
      x: (e.clientX - rect.left) * scaleX,
      y: (e.clientY - rect.top) * scaleY,
    };
  }

  onMouseDown(e) {
    this.isDrawing = true;
    const pos = this.getCanvasPos(e);
    // Start new stroke
    this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: true });
    this.drawPoint(pos);
  }

  onMouseMove(e) {
    const pos = this.getCanvasPos(e);
    this.updateCrosshair(e);
    this.updateCoords(pos);

    if (!this.isDrawing) return;
    this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: false });
    this.drawSegment(pos);
    this.convertToWaveform();
    this.updateWaveformPreview();
    this.updatePointCount();

    // Real-time audio feedback
    if (this.isPreviewPlaying) {
      this.applyWaveformToPreview();
    }
    // Refresh VCO Loop if it's using this drawing
    if (window.vcoLoop) {
      vcoLoop.refreshDrawingOsc();
    }
  }

  onMouseUp() {
    this.isDrawing = false;
  }

  onTouchStart(e) {
    this.isDrawing = true;
    const touch = e.touches[0];
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    const pos = { x: (touch.clientX - rect.left) * scaleX, y: (touch.clientY - rect.top) * scaleY };
    this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: true });
    this.drawPoint(pos);
  }

  onTouchMove(e) {
    if (!this.isDrawing) return;
    const touch = e.touches[0];
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    const pos = { x: (touch.clientX - rect.left) * scaleX, y: (touch.clientY - rect.top) * scaleY };
    this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: false });
    this.drawSegment(pos);
    this.convertToWaveform();
    this.updateWaveformPreview();
    if (this.isPreviewPlaying) {
      this.applyWaveformToPreview();
    }
  }

  // ===== CANVAS RENDERING =====

  drawPoint(pos) {
    const ctx = this.ctx2d;
    ctx.fillStyle = '#00e5ff';
    ctx.beginPath();
    ctx.arc(pos.x, pos.y, 2, 0, Math.PI * 2);
    ctx.fill();
  }

  drawSegment(pos) {
    const ctx = this.ctx2d;
    const pts = this.slots[this.activeSlot].points;
    if (pts.length < 2) return;

    const prev = pts[pts.length - 2];
    ctx.strokeStyle = '#00e5ff';
    ctx.lineWidth = 2;
    ctx.shadowColor = 'rgba(0, 229, 255, 0.5)';
    ctx.shadowBlur = 4;
    ctx.beginPath();
    ctx.moveTo(prev.x, prev.y);
    ctx.lineTo(pos.x, pos.y);
    ctx.stroke();
    ctx.shadowBlur = 0;
  }

  redrawCanvas() {
    if (!this.ctx2d) return;
    const ctx = this.ctx2d;
    const s = this.canvas.width;

    // Background
    ctx.fillStyle = '#111116';
    ctx.fillRect(0, 0, s, s);

    // Grid
    ctx.strokeStyle = '#222228';
    ctx.lineWidth = 1;
    for (let i = 0; i <= 4; i++) {
      const p = (i / 4) * s;
      ctx.beginPath(); ctx.moveTo(p, 0); ctx.lineTo(p, s); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(0, p); ctx.lineTo(s, p); ctx.stroke();
    }

    // Center crosshair
    ctx.strokeStyle = '#333340';
    ctx.beginPath(); ctx.moveTo(s / 2, 0); ctx.lineTo(s / 2, s); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(0, s / 2); ctx.lineTo(s, s / 2); ctx.stroke();

    // Draw all points/strokes
    const pts = this.slots[this.activeSlot].points;
    if (pts.length === 0) return;

    ctx.strokeStyle = '#00e5ff';
    ctx.lineWidth = 2;
    ctx.shadowColor = 'rgba(0, 229, 255, 0.5)';
    ctx.shadowBlur = 4;

    for (let i = 0; i < pts.length; i++) {
      if (pts[i].newStroke || i === 0) {
        ctx.beginPath();
        ctx.moveTo(pts[i].x, pts[i].y);
      } else {
        ctx.lineTo(pts[i].x, pts[i].y);
        ctx.stroke();
        ctx.beginPath();
        ctx.moveTo(pts[i].x, pts[i].y);
      }
    }
    ctx.shadowBlur = 0;
    this.updatePointCount();
  }

  // ===== WAVEFORM CONVERSION (XYscope principle) =====

  convertToWaveform() {
    const slot = this.slots[this.activeSlot];
    const pts = slot.points;
    if (pts.length < 2) {
      slot.waveX = [];
      slot.waveY = [];
      return;
    }

    const s = this.canvas.width;
    const res = this.waveResolution;

    // Normalize points to -1..1 range
    const waveX = new Float32Array(res);
    const waveY = new Float32Array(res);

    // Resample the drawn path to fixed resolution
    // Calculate total path length
    let totalLen = 0;
    const segLengths = [];
    for (let i = 1; i < pts.length; i++) {
      if (pts[i].newStroke) {
        segLengths.push(0);
      } else {
        const dx = pts[i].x - pts[i-1].x;
        const dy = pts[i].y - pts[i-1].y;
        const len = Math.sqrt(dx * dx + dy * dy);
        segLengths.push(len);
        totalLen += len;
      }
    }

    if (totalLen === 0) {
      slot.waveX = Array.from(waveX);
      slot.waveY = Array.from(waveY);
      return;
    }

    // Walk along the path and sample at even intervals
    let accumulated = 0;
    let ptIdx = 1;

    for (let i = 0; i < res; i++) {
      const targetDist = (i / res) * totalLen;

      while (ptIdx < pts.length && accumulated + segLengths[ptIdx - 1] < targetDist) {
        accumulated += segLengths[ptIdx - 1];
        ptIdx++;
      }

      if (ptIdx >= pts.length) ptIdx = pts.length - 1;

      const segLen = segLengths[ptIdx - 1] || 0.001;
      const localT = segLen > 0 ? (targetDist - accumulated) / segLen : 0;
      const p0 = pts[ptIdx - 1];
      const p1 = pts[ptIdx];

      const x = p0.x + (p1.x - p0.x) * Math.max(0, Math.min(1, localT));
      const y = p0.y + (p1.y - p0.y) * Math.max(0, Math.min(1, localT));

      // Normalize to -1..1
      waveX[i] = (x / s) * 2 - 1;
      waveY[i] = -((y / s) * 2 - 1); // Invert Y (canvas Y is top-down)
    }

    slot.waveX = Array.from(waveX);
    slot.waveY = Array.from(waveY);
  }

  // ===== WAVEFORM PREVIEW DISPLAY =====

  updateWaveformPreview() {
    const slot = this.slots[this.activeSlot];
    this.drawWaveCanvas('draw-wave-l', slot.waveX, '#4a9eff');
    this.drawWaveCanvas('draw-wave-r', slot.waveY, '#e84545');
  }

  drawWaveCanvas(canvasId, waveData, color) {
    const canvas = document.getElementById(canvasId);
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const w = canvas.width;
    const h = canvas.height;

    ctx.fillStyle = '#1c1c20';
    ctx.fillRect(0, 0, w, h);

    // Zero line
    ctx.strokeStyle = '#333340';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, h / 2);
    ctx.lineTo(w, h / 2);
    ctx.stroke();

    if (!waveData || waveData.length === 0) return;

    ctx.strokeStyle = color;
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    for (let i = 0; i < w; i++) {
      const idx = Math.floor((i / w) * waveData.length);
      const val = waveData[idx] || 0;
      const y = h / 2 - val * (h / 2 - 2);
      if (i === 0) ctx.moveTo(i, y);
      else ctx.lineTo(i, y);
    }
    ctx.stroke();
  }

  // ===== REAL-TIME AUDIO =====

  togglePreview() {
    if (this.isPreviewPlaying) {
      this.stopPreview();
    } else {
      this.startPreview();
    }
  }

  async startPreview() {
    if (!audioEngine.isInitialized) {
      await audioEngine.init();
    }
    audioEngine.resume();

    const slot = this.slots[this.activeSlot];
    if (slot.waveX.length === 0) {
      this.convertToWaveform();
    }
    if (slot.waveX.length === 0) return;

    this.createPreviewSource();
    this.isPreviewPlaying = true;

    const btn = document.getElementById('draw-preview-btn');
    if (btn) {
      btn.textContent = '■ STOP';
      btn.classList.add('preview-active');
    }
  }

  createPreviewSource() {
    // Stop previous source if any
    this.stopPreviewSource();

    const ctx = audioEngine.ctx;
    const slot = this.slots[this.activeSlot];
    const bufferLength = slot.waveX.length;
    if (bufferLength === 0) return;

    // Create stereo buffer: L=waveX, R=waveY
    const buffer = ctx.createBuffer(2, bufferLength, ctx.sampleRate);
    const lData = buffer.getChannelData(0);
    const rData = buffer.getChannelData(1);
    for (let i = 0; i < bufferLength; i++) {
      lData[i] = slot.waveX[i] || 0;
      rData[i] = (slot.waveY[i] !== undefined) ? slot.waveY[i] : (slot.waveX[i] || 0);
    }

    this.previewGain = ctx.createGain();
    this.previewGain.gain.value = 0.3;
    this.previewGain.connect(audioEngine.masterGain);

    this.previewOsc = ctx.createBufferSource();
    this.previewOsc.buffer = buffer;
    this.previewOsc.loop = true;

    // Set playback rate for 220Hz base
    const baseFreq = ctx.sampleRate / bufferLength;
    this.previewOsc.playbackRate.value = 220 / baseFreq;

    this.previewOsc.connect(this.previewGain);
    this.previewOsc.start();
  }

  stopPreviewSource() {
    if (this.previewOsc) {
      try { this.previewOsc.stop(); } catch(e) {}
      this.previewOsc.disconnect();
      this.previewOsc = null;
    }
    if (this.previewGain) {
      this.previewGain.disconnect();
      this.previewGain = null;
    }
  }

  stopPreview() {
    this.stopPreviewSource();
    this.isPreviewPlaying = false;

    const btn = document.getElementById('draw-preview-btn');
    if (btn) {
      btn.textContent = '♪ PREVIEW';
      btn.classList.remove('preview-active');
    }
  }

  // Update preview audio in real-time while drawing
  applyWaveformToPreview() {
    if (!this.isPreviewPlaying) return;
    // Recreate the source with updated waveform data
    this.createPreviewSource();
  }

  // ===== UI HELPERS =====

  updateCrosshair(e) {
    const rect = this.canvas.getBoundingClientRect();
    const ch = document.getElementById('draw-crosshair-h');
    const cv = document.getElementById('draw-crosshair-v');
    if (ch) ch.style.top = (e.clientY - rect.top) + 'px';
    if (cv) cv.style.left = (e.clientX - rect.left) + 'px';
  }

  updateCoords(pos) {
    const el = document.getElementById('draw-coords');
    if (el) {
      const nx = ((pos.x / this.canvas.width) * 2 - 1).toFixed(2);
      const ny = (-((pos.y / this.canvas.height) * 2 - 1)).toFixed(2);
      el.textContent = `X: ${nx}  Y: ${ny}`;
    }
  }

  updatePointCount() {
    const el = document.getElementById('draw-point-count');
    if (el) {
      el.textContent = `Points: ${this.slots[this.activeSlot].points.length}`;
    }
  }
}

// Global instance
window.drawingMode = new DrawingMode();
