/**
 * DLOSy20 - Drawing Mode
 * Draw shapes on canvas → convert to LR waveform (XYscope principle)
 * Supports multiple drawing slots and per-step waveform assignment
 */

class DrawingMode {
  constructor() {
    // Drawing slots (16 slots, display toggled between 8/16)
    this.slots = [];
    for (let i = 0; i < 16; i++) {
      this.slots.push({ name: `Draw ${i + 1}`, points: [], waveX: [], waveY: [] });
    }
    this.activeSlot = 0;
    this.visibleSlotCount = 8; // 8 or 16
    this.isDrawing = false;
    this.autoSlotCycle = false; // Auto-cycle through slots on each step

    // Pattern bank (8 preset slots of 16 drawings each)
    this.activePattern = 0;
    this.patternBank = [];
    for (let i = 0; i < 8; i++) {
      this.patternBank.push(null);
    }

    // Tool state
    this.toolMode = 'draw'; // 'draw' or 'erase'
    this.eraserRadius = 15;

    // Canvas
    this.canvas = null;
    this.ctx2d = null;
    this.canvasSize = 256;

    // Audio: real-time preview oscillator using PeriodicWave
    this.previewOsc = null;
    this.previewGain = null;
    this.isPreviewPlaying = false;

    // Waveform resolution
    this.waveResolution = 256;
  }

  init() {
    this.buildUI();
    this.bindControls();
    this.buildPatternBankUI();
  }

  // ===== UI =====

  buildUI() {
    const container = document.getElementById('drawing-panel');
    if (!container) return;

    container.innerHTML = `
      <div class="panel-title">
        DRAWING MODE
        <div class="draw-header-controls">
          <button id="draw-tool-draw" class="small-btn ${this.toolMode === 'draw' ? 'active' : ''}" title="Draw Tool">DRAW</button>
          <button id="draw-tool-erase" class="small-btn ${this.toolMode === 'erase' ? 'active' : ''}" title="Eraser Tool">ERASE</button>
          <span class="seq-separator">|</span>
          <button id="draw-slots-8" class="small-btn step-count-btn active" data-slots="8">8</button>
          <button id="draw-slots-16" class="small-btn step-count-btn" data-slots="16">16</button>
          <span class="seq-separator">|</span>
          <button id="draw-auto-cycle" class="small-btn">AUTO CYCLE</button>
          <button id="draw-preview-btn" class="small-btn">♪ PREVIEW</button>
          <button id="draw-clear-btn" class="small-btn">CLEAR</button>
        </div>
      </div>
      <div class="draw-slot-tabs" id="draw-slot-tabs">
        <!-- generated by JS -->
      </div>
      <div class="draw-main-area">
        <div class="draw-canvas-wrapper">
          <canvas id="draw-canvas" width="256" height="256"></canvas>
          <div class="draw-crosshair-h" id="draw-crosshair-h"></div>
          <div class="draw-crosshair-v" id="draw-crosshair-v"></div>
        </div>
        <div class="draw-waveform-preview">
          <div class="draw-wave-label">L (X)</div>
          <canvas id="draw-wave-l" width="256" height="48"></canvas>
          <div class="draw-wave-label">R (Y)</div>
          <canvas id="draw-wave-r" width="256" height="48"></canvas>
        </div>
      </div>
      <div class="draw-info-bar">
        <span id="draw-point-count" class="draw-info">Points: 0</span>
        <span id="draw-coords" class="draw-info"></span>
      </div>
    `;

    this.buildSlotTabs();
    this.initCanvas();
  }

  buildSlotTabs() {
    const container = document.getElementById('draw-slot-tabs');
    if (!container) return;
    container.innerHTML = '';

    for (let i = 0; i < this.visibleSlotCount; i++) {
      const slot = this.slots[i];
      const tab = document.createElement('button');
      tab.className = 'draw-slot-tab' + (i === this.activeSlot ? ' active' : '');
      tab.textContent = slot.name;
      tab.dataset.slot = i;
      tab.addEventListener('click', () => {
        this.switchSlot(i);
      });
      container.appendChild(tab);
    }

    // Clamp activeSlot if needed
    if (this.activeSlot >= this.visibleSlotCount) {
      this.switchSlot(0);
    }
  }

  switchSlot(index) {
    if (index < 0 || index >= this.visibleSlotCount) return;
    this.activeSlot = index;
    
    document.querySelectorAll('.draw-slot-tab').forEach((t, i) => {
      t.classList.toggle('active', i === index);
    });
    
    this.redrawCanvas();
    this.updateWaveformPreview();
    
    // Switch VCO Loop audio buffer if running in drawing mode
    if (window.vcoLoop && vcoLoop.isOscRunning && vcoLoop.isDrawingOsc) {
      vcoLoop.switchDrawBuffer(this.activeSlot);
    }
    // Switch Arpeggiator drawing buffer if running in drawing mode
    if (window.arpeggiator && arpeggiator.refreshDrawingOsc) {
      arpeggiator.refreshDrawingOsc();
    }
  }

  // ===== PATTERN BANK =====
  switchPattern(index) {
    if (index === this.activePattern) return;
    
    // Save current slots to the active bank
    const savedSlots = this.slots.map(s => JSON.parse(JSON.stringify(s)));
    this.patternBank[this.activePattern] = {
      visibleSlotCount: this.visibleSlotCount,
      slots: savedSlots
    };

    // Load target bank
    this.activePattern = index;
    const target = this.patternBank[index];
    
    if (target) {
      this.visibleSlotCount = target.visibleSlotCount || 8;
      this.slots = target.slots.map(slot => ({
        name: slot.name,
        points: slot.points.map(p => ({ x: p.x, y: p.y })),
        waveX: [...slot.waveX],
        waveY: [...slot.waveY],
      }));
    } else {
      // Re-initialize to default blank slots
      this.slots = [];
      for (let i = 0; i < 16; i++) {
        this.slots.push({ name: `Draw ${i + 1}`, points: [], waveX: [], waveY: [] });
      }
      this.visibleSlotCount = 8;
    }

    this.activeSlot = 0;
    this.buildSlotTabs();
    this.redrawCanvas();
    this.updateWaveformPreview();
    this.buildPatternBankUI();

    // Update slot count buttons
    document.getElementById('draw-slots-8')?.classList.toggle('active', this.visibleSlotCount === 8);
    document.getElementById('draw-slots-16')?.classList.toggle('active', this.visibleSlotCount === 16);

    // Auto-save preset if manager exists
    if (window.presetManager) presetManager.autoSave();
  }

  buildPatternBankUI() {
    const panel = document.getElementById('drawing-panel');
    if (!panel) return;
    let bankDiv = panel.querySelector('.pattern-bank');
    if (!bankDiv) {
      // Insert after the header element
      const header = panel.querySelector('.panel-title');
      bankDiv = document.createElement('div');
      bankDiv.className = 'pattern-bank';
      if (header) {
        header.after(bankDiv);
      } else {
        panel.insertBefore(bankDiv, panel.firstChild);
      }
    }
    bankDiv.innerHTML = '';
    for (let i = 0; i < 8; i++) {
      const btn = document.createElement('button');
      btn.className = 'pattern-btn' + (i === this.activePattern ? ' active' : '');
      btn.textContent = i + 1;
      btn.addEventListener('click', () => this.switchPattern(i));
      bankDiv.appendChild(btn);
    }
  }

  initCanvas() {
    this.canvas = document.getElementById('draw-canvas');
    if (!this.canvas) return;
    this.ctx2d = this.canvas.getContext('2d');

    this.canvas.addEventListener('mousedown', (e) => this.onMouseDown(e));
    this.canvas.addEventListener('mousemove', (e) => this.onMouseMove(e));
    this.canvas.addEventListener('mouseup', () => this.onMouseUp());
    this.canvas.addEventListener('mouseleave', () => this.onMouseUp());

    // Touch
    this.canvas.addEventListener('touchstart', (e) => { e.preventDefault(); this.onTouchStart(e); }, { passive: false });
    this.canvas.addEventListener('touchmove', (e) => { e.preventDefault(); this.onTouchMove(e); }, { passive: false });
    this.canvas.addEventListener('touchend', () => this.onMouseUp());

    this.redrawCanvas();
  }

  bindControls() {
    // Tool selection
    document.getElementById('draw-tool-draw')?.addEventListener('click', (e) => {
      this.setToolMode('draw');
      document.getElementById('draw-tool-draw').classList.add('active');
      document.getElementById('draw-tool-erase').classList.remove('active');
    });
    
    document.getElementById('draw-tool-erase')?.addEventListener('click', (e) => {
      this.setToolMode('erase');
      document.getElementById('draw-tool-erase').classList.add('active');
      document.getElementById('draw-tool-draw').classList.remove('active');
    });

    document.getElementById('draw-clear-btn')?.addEventListener('click', () => {
      this.slots[this.activeSlot].points = [];
      this.slots[this.activeSlot].waveX = [];
      this.slots[this.activeSlot].waveY = [];
      this.redrawCanvas();
      this.updateWaveformPreview();
      this.updatePointCount();
    });

    document.getElementById('draw-preview-btn')?.addEventListener('click', () => {
      this.togglePreview();
    });

    // Auto-cycle ON/OFF toggle
    document.getElementById('draw-auto-cycle')?.addEventListener('click', () => {
      this.autoSlotCycle = !this.autoSlotCycle;
      const btn = document.getElementById('draw-auto-cycle');
      if (btn) {
        btn.classList.toggle('vco-on', this.autoSlotCycle);
      }
    });

    // Slot count toggle (8 / 16)
    document.getElementById('draw-slots-8')?.addEventListener('click', () => {
      this.visibleSlotCount = 8;
      document.getElementById('draw-slots-8')?.classList.add('active');
      document.getElementById('draw-slots-16')?.classList.remove('active');
      this.buildSlotTabs();
    });

    document.getElementById('draw-slots-16')?.addEventListener('click', () => {
      this.visibleSlotCount = 16;
      document.getElementById('draw-slots-16')?.classList.add('active');
      document.getElementById('draw-slots-8')?.classList.remove('active');
      this.buildSlotTabs();
    });
  }

  // Advance to next slot (called from step sequencer on each step tick)
  advanceSlot() {
    if (!this.autoSlotCycle) return;
    const nextSlot = (this.activeSlot + 1) % this.visibleSlotCount;
    this.switchSlot(nextSlot);
  }

  // Import SVG path data (e.g. from a glyph database) into active slot
  importSVGPath(svgPathData) {
    if (!this.canvas || !this.ctx2d) return;

    const size = this.canvasSize; // 256
    const svgSize = 1000; // viewBox
    const scale = size / svgSize;

    const offCanvas = document.createElement('canvas');
    offCanvas.width = size;
    offCanvas.height = size;
    const offCtx = offCanvas.getContext('2d', { willReadFrequently: true });

    offCtx.save();
    offCtx.scale(scale, scale);
    const path = new Path2D(svgPathData);
    offCtx.lineWidth = 3 / scale;
    offCtx.strokeStyle = '#fff';
    offCtx.stroke(path);
    offCtx.restore();

    return this._applyTracedCanvas(offCtx, size);
  }

  // Render any character / symbol with the browser's own font and trace its
  // outline into the active slot. This is the fully-local replacement for the
  // glyph-database API: no Unicode table, no network — works for anything the
  // installed fonts can draw.
  importGlyphChar(char, fontFamily) {
    if (!this.canvas || !this.ctx2d || !char) return false;

    const size = this.canvasSize;
    const font = fontFamily || 'sans-serif';

    const offCanvas = document.createElement('canvas');
    offCanvas.width = size;
    offCanvas.height = size;
    const offCtx = offCanvas.getContext('2d', { willReadFrequently: true });

    offCtx.textAlign = 'center';
    offCtx.textBaseline = 'middle';

    // Fit the glyph to the canvas
    let fontPx = Math.floor(size * 0.8);
    offCtx.font = `${fontPx}px ${font}`;
    const m = offCtx.measureText(char);
    const w = m.width || fontPx;
    const ascent = m.actualBoundingBoxAscent || fontPx * 0.7;
    const descent = m.actualBoundingBoxDescent || fontPx * 0.2;
    const maxDim = Math.max(w, ascent + descent);
    if (maxDim > size * 0.85) {
      fontPx = Math.max(8, Math.floor(fontPx * (size * 0.85) / maxDim));
      offCtx.font = `${fontPx}px ${font}`;
    }

    // Stroke the glyph OUTLINE → a clean traceable contour (like the SVG case)
    offCtx.lineWidth = 2;
    offCtx.lineJoin = 'round';
    offCtx.strokeStyle = '#fff';
    offCtx.strokeText(char, size / 2, size / 2);

    return this._applyTracedCanvas(offCtx, size);
  }

  // Shared: trace the white shape on an offscreen canvas into an ordered point
  // path and load it into the active slot. Used by SVG import + glyph rendering.
  _applyTracedCanvas(offCtx, size) {
    const data = offCtx.getImageData(0, 0, size, size).data;
    const points = [];

    // Collect contour pixels (sampled every 2px for a clean, light outline)
    for (let y = 0; y < size; y += 2) {
      for (let x = 0; x < size; x += 2) {
        if (data[(y * size + x) * 4 + 3] > 128) points.push({ x, y });
      }
    }
    if (points.length === 0) return false;

    // Nearest-neighbor sort into a continuous path
    const sortedPoints = [points[0]];
    const used = new Set([0]);
    for (let i = 1; i < points.length; i++) {
      const last = sortedPoints[sortedPoints.length - 1];
      let nearest = -1, nearestDist = Infinity;
      for (let j = 0; j < points.length; j++) {
        if (used.has(j)) continue;
        const dx = points[j].x - last.x;
        const dy = points[j].y - last.y;
        const dist = dx * dx + dy * dy;
        if (dist < nearestDist) { nearestDist = dist; nearest = j; }
      }
      if (nearest === -1) break;
      used.add(nearest);
      sortedPoints.push(points[nearest]);
    }

    const slot = this.slots[this.activeSlot];
    slot.points = sortedPoints;

    this.redrawCanvas();
    this.convertToWaveform();
    this.updateWaveformPreview();
    this.updatePointCount();

    if (window.vcoLoop && vcoLoop.isOscRunning && vcoLoop.isDrawingOsc) {
      vcoLoop.refreshDrawingOsc();
    }
    if (window.arpeggiator && arpeggiator.refreshDrawingOsc) {
      arpeggiator.refreshDrawingOsc();
    }
    return true;
  }

  // ===== DRAWING / ERASING =====

  setToolMode(mode) {
    this.toolMode = mode;
    if (this.canvas) {
      if (mode === 'erase') {
        this.canvas.style.cursor = 'crosshair';
      } else {
        this.canvas.style.cursor = 'default';
      }
    }
  }

  getCanvasPos(e) {
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    return {
      x: (e.clientX - rect.left) * scaleX,
      y: (e.clientY - rect.top) * scaleY,
    };
  }

  erasePoints(pos) {
    const pts = this.slots[this.activeSlot].points;
    let erased = false;
    
    // Iterate forwards to properly split strokes
    for (let i = 0; i < pts.length; i++) {
      const p = pts[i];
      const dx = p.x - pos.x;
      const dy = p.y - pos.y;
      
      // If the point is within the eraser radius
      if (dx * dx + dy * dy < this.eraserRadius * this.eraserRadius) {
        // If there's a next point and it's NOT a new stroke,
        // we must make it the start of a new stroke to break the path.
        if (i < pts.length - 1 && !pts[i+1].newStroke) {
          pts[i+1].newStroke = true;
        }
        
        // Remove the current point
        pts.splice(i, 1);
        erased = true;
        
        // Decrement i since we modified the array in place
        i--;
      }
    }
    
    if (erased) {
      this.redrawCanvas();
      this.convertToWaveform();
      this.updateWaveformPreview();
      this.updatePointCount();
      if (this.isPreviewPlaying) {
        this.applyWaveformToPreview();
      }
      if (window.vcoLoop) {
        vcoLoop.refreshDrawingOsc();
      }
      if (window.arpeggiator) {
        arpeggiator.refreshDrawingOsc();
      }
    }
    return erased;
  }

  onMouseDown(e) {
    this.isDrawing = true;
    const pos = this.getCanvasPos(e);
    
    if (this.toolMode === 'erase') {
      this.erasePoints(pos);
    } else {
      // Start new stroke
      this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: true });
      this.drawPoint(pos);
    }
  }

  onMouseMove(e) {
    const pos = this.getCanvasPos(e);
    this.updateCrosshair(e);
    this.updateCoords(pos);

    if (!this.isDrawing) return;

    if (this.toolMode === 'erase') {
      this.erasePoints(pos);
    } else {
      this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: false });
      this.drawSegment(pos);
      this.convertToWaveform();
      this.updateWaveformPreview();
      this.updatePointCount();

      // Real-time audio feedback
      if (this.isPreviewPlaying) {
        this.applyWaveformToPreview();
      }
      // Refresh VCO Loop if it's using this drawing
      if (window.vcoLoop) {
        vcoLoop.refreshDrawingOsc();
      }
      // Refresh Arpeggiator if it's using this drawing (real-time)
      if (window.arpeggiator) {
        arpeggiator.refreshDrawingOsc();
      }
    }
  }

  onMouseUp() {
    this.isDrawing = false;
  }

  onTouchStart(e) {
    this.isDrawing = true;
    const touch = e.touches[0];
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    const pos = { x: (touch.clientX - rect.left) * scaleX, y: (touch.clientY - rect.top) * scaleY };
    
    if (this.toolMode === 'erase') {
      this.erasePoints(pos);
    } else {
      this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: true });
      this.drawPoint(pos);
    }
  }

  onTouchMove(e) {
    if (!this.isDrawing) return;
    const touch = e.touches[0];
    const rect = this.canvas.getBoundingClientRect();
    const scaleX = this.canvas.width / rect.width;
    const scaleY = this.canvas.height / rect.height;
    const pos = { x: (touch.clientX - rect.left) * scaleX, y: (touch.clientY - rect.top) * scaleY };
    
    if (this.toolMode === 'erase') {
      this.erasePoints(pos);
    } else {
      this.slots[this.activeSlot].points.push({ x: pos.x, y: pos.y, newStroke: false });
      this.drawSegment(pos);
      this.convertToWaveform();
      this.updateWaveformPreview();
      if (this.isPreviewPlaying) {
        this.applyWaveformToPreview();
      }
      if (window.vcoLoop) {
        vcoLoop.refreshDrawingOsc();
      }
      if (window.arpeggiator) {
        arpeggiator.refreshDrawingOsc();
      }
    }
  }

  // ===== CANVAS RENDERING =====

  drawPoint(pos) {
    const ctx = this.ctx2d;
    ctx.fillStyle = '#00e5ff';
    ctx.beginPath();
    ctx.arc(pos.x, pos.y, 2, 0, Math.PI * 2);
    ctx.fill();
  }

  drawSegment(pos) {
    const ctx = this.ctx2d;
    const pts = this.slots[this.activeSlot].points;
    if (pts.length < 2) return;

    const prev = pts[pts.length - 2];
    ctx.strokeStyle = '#00e5ff';
    ctx.lineWidth = 2;
    ctx.shadowColor = 'rgba(0, 229, 255, 0.5)';
    ctx.shadowBlur = 4;
    ctx.beginPath();
    ctx.moveTo(prev.x, prev.y);
    ctx.lineTo(pos.x, pos.y);
    ctx.stroke();
    ctx.shadowBlur = 0;
  }

  redrawCanvas() {
    if (!this.ctx2d) return;
    const ctx = this.ctx2d;
    const s = this.canvas.width;

    // Background
    ctx.fillStyle = '#111116';
    ctx.fillRect(0, 0, s, s);

    // Grid
    ctx.strokeStyle = '#222228';
    ctx.lineWidth = 1;
    for (let i = 0; i <= 4; i++) {
      const p = (i / 4) * s;
      ctx.beginPath(); ctx.moveTo(p, 0); ctx.lineTo(p, s); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(0, p); ctx.lineTo(s, p); ctx.stroke();
    }

    // Center crosshair
    ctx.strokeStyle = '#333340';
    ctx.beginPath(); ctx.moveTo(s / 2, 0); ctx.lineTo(s / 2, s); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(0, s / 2); ctx.lineTo(s, s / 2); ctx.stroke();

    // Draw all points/strokes
    const pts = this.slots[this.activeSlot].points;
    if (pts.length === 0) return;

    ctx.strokeStyle = '#00e5ff';
    ctx.lineWidth = 2;
    ctx.shadowColor = 'rgba(0, 229, 255, 0.5)';
    ctx.shadowBlur = 4;

    for (let i = 0; i < pts.length; i++) {
      if (pts[i].newStroke || i === 0) {
        ctx.beginPath();
        ctx.moveTo(pts[i].x, pts[i].y);
      } else {
        ctx.lineTo(pts[i].x, pts[i].y);
        ctx.stroke();
        ctx.beginPath();
        ctx.moveTo(pts[i].x, pts[i].y);
      }
    }
    ctx.shadowBlur = 0;
    this.updatePointCount();
  }

  // ===== WAVEFORM CONVERSION (XYscope principle) =====

  convertToWaveform() {
    const slot = this.slots[this.activeSlot];
    const pts = slot.points;
    if (pts.length < 2) {
      slot.waveX = [];
      slot.waveY = [];
      return;
    }

    const s = this.canvas.width;
    const res = this.waveResolution;

    // Normalize points to -1..1 range
    const waveX = new Float32Array(res);
    const waveY = new Float32Array(res);

    // Resample the drawn path to fixed resolution
    // Calculate total path length
    let totalLen = 0;
    const segLengths = [];
    for (let i = 1; i < pts.length; i++) {
      if (pts[i].newStroke) {
        segLengths.push(0);
      } else {
        const dx = pts[i].x - pts[i-1].x;
        const dy = pts[i].y - pts[i-1].y;
        const len = Math.sqrt(dx * dx + dy * dy);
        segLengths.push(len);
        totalLen += len;
      }
    }

    if (totalLen === 0) {
      slot.waveX = Array.from(waveX);
      slot.waveY = Array.from(waveY);
      return;
    }

    // Walk along the path and sample at even intervals
    let accumulated = 0;
    let ptIdx = 1;

    for (let i = 0; i < res; i++) {
      const targetDist = (i / res) * totalLen;

      while (ptIdx < pts.length && accumulated + segLengths[ptIdx - 1] < targetDist) {
        accumulated += segLengths[ptIdx - 1];
        ptIdx++;
      }

      if (ptIdx >= pts.length) ptIdx = pts.length - 1;

      const segLen = segLengths[ptIdx - 1] || 0.001;
      const localT = segLen > 0 ? (targetDist - accumulated) / segLen : 0;
      const p0 = pts[ptIdx - 1];
      const p1 = pts[ptIdx];

      const x = p0.x + (p1.x - p0.x) * Math.max(0, Math.min(1, localT));
      const y = p0.y + (p1.y - p0.y) * Math.max(0, Math.min(1, localT));

      // Normalize to -1..1
      waveX[i] = (x / s) * 2 - 1;
      waveY[i] = -((y / s) * 2 - 1); // Invert Y (canvas Y is top-down)
    }

    slot.waveX = Array.from(waveX);
    slot.waveY = Array.from(waveY);
  }

  // ===== WAVEFORM PREVIEW DISPLAY =====

  updateWaveformPreview() {
    const slot = this.slots[this.activeSlot];
    this.drawWaveCanvas('draw-wave-l', slot.waveX, '#4a9eff');
    this.drawWaveCanvas('draw-wave-r', slot.waveY, '#e84545');
  }

  drawWaveCanvas(canvasId, waveData, color) {
    const canvas = document.getElementById(canvasId);
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const w = canvas.width;
    const h = canvas.height;

    ctx.fillStyle = '#1c1c20';
    ctx.fillRect(0, 0, w, h);

    // Zero line
    ctx.strokeStyle = '#333340';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, h / 2);
    ctx.lineTo(w, h / 2);
    ctx.stroke();

    if (!waveData || waveData.length === 0) return;

    ctx.strokeStyle = color;
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    for (let i = 0; i < w; i++) {
      const idx = Math.floor((i / w) * waveData.length);
      const val = waveData[idx] || 0;
      const y = h / 2 - val * (h / 2 - 2);
      if (i === 0) ctx.moveTo(i, y);
      else ctx.lineTo(i, y);
    }
    ctx.stroke();
  }

  // ===== REAL-TIME AUDIO =====

  togglePreview() {
    if (this.isPreviewPlaying) {
      this.stopPreview();
    } else {
      this.startPreview();
    }
  }

  async startPreview() {
    if (!audioEngine.isInitialized) {
      await audioEngine.init();
    }
    audioEngine.resume();

    const slot = this.slots[this.activeSlot];
    if (slot.waveX.length === 0) {
      this.convertToWaveform();
    }
    if (slot.waveX.length === 0) return;

    this.createPreviewSource();
    this.isPreviewPlaying = true;

    const btn = document.getElementById('draw-preview-btn');
    if (btn) {
      btn.textContent = '■ STOP';
      btn.classList.add('preview-active');
    }
  }

  createPreviewSource() {
    // Stop previous source if any
    this.stopPreviewSource();

    const ctx = audioEngine.ctx;
    const slot = this.slots[this.activeSlot];
    const bufferLength = slot.waveX.length;
    if (bufferLength === 0) return;

    // Create stereo buffer: L=waveX, R=waveY
    const buffer = ctx.createBuffer(2, bufferLength, ctx.sampleRate);
    const lData = buffer.getChannelData(0);
    const rData = buffer.getChannelData(1);
    for (let i = 0; i < bufferLength; i++) {
      lData[i] = slot.waveX[i] || 0;
      rData[i] = (slot.waveY[i] !== undefined) ? slot.waveY[i] : (slot.waveX[i] || 0);
    }

    this.previewGain = ctx.createGain();
    this.previewGain.gain.value = 0.3;
    this.previewGain.connect(audioEngine.masterGain);

    this.previewOsc = ctx.createBufferSource();
    this.previewOsc.buffer = buffer;
    this.previewOsc.loop = true;

    // Set playback rate for 220Hz base
    const baseFreq = ctx.sampleRate / bufferLength;
    this.previewOsc.playbackRate.value = 220 / baseFreq;

    this.previewOsc.connect(this.previewGain);
    this.previewOsc.start();
  }

  stopPreviewSource() {
    if (this.previewOsc) {
      try { this.previewOsc.stop(); } catch(e) {}
      this.previewOsc.disconnect();
      this.previewOsc = null;
    }
    if (this.previewGain) {
      this.previewGain.disconnect();
      this.previewGain = null;
    }
  }

  stopPreview() {
    this.stopPreviewSource();
    this.isPreviewPlaying = false;

    const btn = document.getElementById('draw-preview-btn');
    if (btn) {
      btn.textContent = '♪ PREVIEW';
      btn.classList.remove('preview-active');
    }
  }

  // Update preview audio in real-time while drawing
  applyWaveformToPreview() {
    if (!this.isPreviewPlaying) return;
    // Recreate the source with updated waveform data
    this.createPreviewSource();
  }

  // ===== UI HELPERS =====

  updateCrosshair(e) {
    const rect = this.canvas.getBoundingClientRect();
    const ch = document.getElementById('draw-crosshair-h');
    const cv = document.getElementById('draw-crosshair-v');
    if (ch) ch.style.top = (e.clientY - rect.top) + 'px';
    if (cv) cv.style.left = (e.clientX - rect.left) + 'px';
  }

  updateCoords(pos) {
    const el = document.getElementById('draw-coords');
    if (el) {
      const nx = ((pos.x / this.canvas.width) * 2 - 1).toFixed(2);
      const ny = (-((pos.y / this.canvas.height) * 2 - 1)).toFixed(2);
      el.textContent = `X: ${nx}  Y: ${ny}`;
    }
  }

  updatePointCount() {
    const el = document.getElementById('draw-point-count');
    if (el) {
      el.textContent = `Points: ${this.slots[this.activeSlot].points.length}`;
    }
  }
}

// Global instance
window.drawingMode = new DrawingMode();
